name: Deploy API to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: zip -r hb-mdm-api.zip . -x "venv/*" ".git/*"
      - uses: actions/upload-artifact@v4
        with:
          name: api-zip
          path: hb-mdm-api.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: api-zip
      - uses: azure/webapps-deploy@v3
        with:
          app-name: himmelblau-linux-mdm
          slot-name: Production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: hb-mdm-api.zip
